from abakit.lib.Controllers.Controller import Controller
class BrainShapeController(Controller):
    def insert_shapes(self):
        ...
    
    def get_shapes(self):
        ...
    
    def get_available_shapes(self):
        ...
    ...