channels:
  - pytorch
  - conda-forge
dependencies:
  # install dependencies
  - python=3
  - numpy
  - pytorch

  # dev dependencies
  ## code
  - black
  - pylint
  - pytest
  ## demo
  - jupyterlab
  - jedi<0.18.0 # https://github.com/ipython/ipython/issues/12740
  - plotly
  - scipy
  ## doc
  - m2r2
  - sphinx
  - sphinxcontrib-apidoc
  ## build
  - setuptools
  - wheel

  # dependencies through pip
  - pip
  - pip:
    - git+https://github.com/facebookresearch/pytorch3d.git
